### ISSUE TITLE
Instructions to compile for Linux

### ISSUE THREAD

**Issue by heichwald** [horego/BurstPlotConverter#1]
Hello,

could you include the steps to have it running on Linux.
Like compilation.

Or build a binary for common Linux distribs like ubuntu?

Thanks

**Comment by horego** [comment]
Hey,

the only thing you need is the .net core 2.0 runtime and
the compiled files of Burst PlotConverter (see release section: BurstPlotConverter**Core**.zip).

install the runtime unzip the archive and you can start the program by typing sth like
./dotnet Horego.BurstPlotConverter.dll

for compilation you need the full sdk: https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/sdk-2.1.4
But there is no reason to do this.

**Comment by heichwald** [comment]
@horego : I am still having trouble:
 I run:
`dotnet Horego.BurstPlotConverter.dll` and I got:
Did you mean to run dotnet SDK commands?

I install dotnet runtime core 2.1 for ubuntu 16.04.

Does it matter if it is 2.0 or 2.1?

**Comment by horego** [comment]
Do you have any troubles?

You should install .net core 2.0.x
Maybe this articles can help you:
https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/runtime-2.0.5
https://docs.microsoft.com/de-de/dotnet/core/tools/dotnet-run?tabs=netcore21

You can run the program by "dotnet Horego.BurstPlotConverter.dll" without ./

**Comment by heichwald** [comment]
No it was my mistake, i was not in the right folder...
It works well.
Thanks, I like it
